controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_routes:
    resource: ../src/Controller/
    type: attribute
    prefix: /api/v1
